version: '3'

networks:
  babyborn:

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - babyborn

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - .:/var/www
    networks:
      - babyborn

#  mysql:
#    image: mysql:8
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
#    environment:
#      - MYSQL_PASSWORD=sveta
#      - MYSQL_USER=sveta
#      - MYSQL_DATABASE=babyborn
#    networks:
#      - babyborn

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
